### ISSUE TITLE
Login error: User or connection doesn't exist.

### ISSUE THREAD

**Issue by jjqqkk** [fxcm/ForexConnectAPI#24]
Hi, I constantly got the following error in the past few hours: 

`SessionStatus onLoginFailed: User or connection doesn't exist.`

Please help to look into the problem, thanks.

**Comment by FXCMAPI** [comment]
Dear client

Please try again.
If you still have issue, please provide error logs.

Best regards
Lei


The Stratos group of companies includes Stratos Markets Limited<http://www.fxcm.com/uk/>, Stratos Europe Ltd<http://www.fxcm.com/eu/>, Stratos Trading Pty. Limited<http://www.fxcm.com/au/>, Stratos South Africa (Pty) Ltd<http://www.fxcm.com/za/>, Stratos Global LLC<https://www.fxcm.com/markets>, as well as other affiliates [the "Stratos Group"]. The Stratos Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom.

Stratos Markets Limited is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877.

Risk Warning: CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. 66% of retail investor accounts lose money when trading CFDs with this provider. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Stratos Europe Ltd (trading as "FXCM" or "FXCM EU"), previously FXCM EU LTD is a Cyprus Investment Firm ("CIF") registered with the Cyprus Department of Registrar of Companies (HE 405643) and authorised and regulated by the Cyprus Securities and Exchange Commission ("CySEC") under license number 392/20.

Risk Warning: CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. 70% of retail investor accounts lose money when trading CFDs with this provider. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Stratos Trading Pty. Limited (trading as "FXCM") (AFSL 309763, ABN 31 121 934 432) is regulated by the Australian Securities and Investments Commission. The information provided by FXCM is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/website-terms-and-conditions/>.

Risk Warning: By trading, you could sustain a total loss of your deposited funds. The products may not be suitable for all investors. Please ensure that you fully understand the risks involved. If you decide to trade products offered by FXCM, you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, Target Market Determination<https://www.fxcm.com/au/legal/target-market-determination/> and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>.

Stratos South Africa (Pty) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534.

Risk Warning: Our service includes products that are traded on margin and carry a risk of losses in excess of your deposited funds. The products may not be suitable for all investors. Please ensure that you fully understand the risks involved. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act.

Stratos Global LLC is incorporated in St Vincent and the Grenadines with company registration No. 1776 LLC 2022 and is an operating subsidiary within the Stratos Group of companies (collectively, the "Stratos Group" or "FXCM"). FXCM is not required to hold any financial services license or authorization in St Vincent and the Grenadines to offer its products and services.

Risk Warning: Losses can exceed deposited funds.

Information Security on Internet: To protect your privacy, do not access your trading account via public or shared computers or save your password locally in any computer or mobile device after logging in. We will never ask you to send any of your personal information such as account number and password to us directly via e-mails.
From: JJQQKK ***@***.***>
Sent: Thursday, January 18, 2024 8:55 PM
To: fxcm/ForexConnectAPI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fxcm/ForexConnectAPI] Login error: User or connection doesn't exist. (Issue #24)


Hi, I constantly got the following error in the past few hours:

SessionStatus onLoginFailed: User or connection doesn't exist.

Please help to look into the problem, thanks.

**Comment by jjqqkk** [comment]
Working now, fantastic, thank you!
